# sudo : 관리자 권한 찾기
#sudo: required

os: linux

# 언어(플랫폼)선택
language: generic

# ----------------------------
# *** 우분투 릴리즈별 코드명  ***
# Xenial Xerus (16.04)
# Yakkety Yak (16.10)
# Zesty Zapus (17.04)
# Artful Aardvark (17.10)
# Bionic Beaver (18.04)
# ----------------------------
dist: xenial

# docker 환경 구성
services:
    - docker

# Script 를 실행 할수 있는 환경
before_install:
    - echo "start Creating an image with dockfile."
    - docker build -t jsjung/react .

# 실행할 Script(테스트 실행)
script:
    - docker run -e CI=true jsjung/react npm run test -- --coverage

# 테스트 성공후 할일
after_success:
    - echo "Test Success"

deploy:
    provider: elasticbeanstalk
    region: "ap-northeast-2"
    app: "docker-test"
    env: "DockerTest-env-1"
    bucket_name: "elasticbeanstalk-ap-northeast-2-721913135912"
    bucket_path: "docker-test"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_ACCESS_KEY
